version: '3.6'

services:
  conference:
    image: ${DOCKER_IMAGE_NAME:-ilha/bothub-conference}:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - default
